"""Research workflows for real-data strategy studies."""

from quantlab.research.defensive_momentum import (
    DefensiveMomentumConfig,
    DefensiveMomentumResult,
    FrozenDefensiveMomentumConfig,
    FrozenMonthlyRobustnessResult,
    append_defensive_outcome,
    compute_defensive_momentum_decision,
    compute_defensive_momentum_outcome,
    load_defensive_momentum_csv,
    run_defensive_momentum_study,
    run_frozen_monthly_robustness,
    verify_defensive_outcome_ledger,
)
from quantlab.research.execution_timing import (
    ExecutionTimingConfig,
    ExecutionTimingResult,
    load_adjusted_ohlc_csv,
    run_execution_timing_audit,
)
from quantlab.research.experiment_config import (
    CostModel,
    DatasetReference,
    EvaluationSettings,
    ExecutionSettings,
    MarketMakingExperimentConfig,
    ResearchPeriod,
    StrategySettings,
    load_market_making_experiment_config,
)
from quantlab.research.leveraged_trend import (
    LeveragedTrendConfig,
    LeveragedTrendResult,
    load_leveraged_etf_csv,
    run_leveraged_trend_study,
)
from quantlab.research.leveraged_trend_stress import (
    LeveragedTrendStressConfig,
    LeveragedTrendStressResult,
    load_qqq_fred_csv,
    run_leveraged_trend_stress,
)
from quantlab.research.market_making_study import (
    MarketMakingStudyResult,
    calibrate_market_data,
    chronological_split,
    chronological_split_from_config,
    run_market_making_study,
)
from quantlab.research.paper_trading import (
    FrozenPaperConfig,
    append_paper_decision,
    append_paper_outcome,
    compute_paper_decision,
    compute_paper_outcome,
    verify_outcome_ledger,
    verify_paper_ledger,
)
from quantlab.research.registry import register_experiment
from quantlab.research.valuation_regime import (
    RobustnessResult,
    TearSheet,
    ValuationRegimeConfig,
    ValuationRegimeResult,
    load_shiller_sp500_csv,
    run_valuation_regime_walk_forward,
)

__all__ = [
    "CostModel",
    "DatasetReference",
    "EvaluationSettings",
    "ExecutionSettings",
    "ExecutionTimingConfig",
    "ExecutionTimingResult",
    "DefensiveMomentumConfig",
    "DefensiveMomentumResult",
    "FrozenDefensiveMomentumConfig",
    "FrozenMonthlyRobustnessResult",
    "append_defensive_outcome",
    "FrozenPaperConfig",
    "MarketMakingExperimentConfig",
    "MarketMakingStudyResult",
    "ResearchPeriod",
    "StrategySettings",
    "LeveragedTrendConfig",
    "LeveragedTrendResult",
    "LeveragedTrendStressConfig",
    "LeveragedTrendStressResult",
    "RobustnessResult",
    "TearSheet",
    "ValuationRegimeConfig",
    "ValuationRegimeResult",
    "load_leveraged_etf_csv",
    "load_defensive_momentum_csv",
    "load_adjusted_ohlc_csv",
    "load_qqq_fred_csv",
    "load_shiller_sp500_csv",
    "load_market_making_experiment_config",
    "calibrate_market_data",
    "append_paper_decision",
    "append_paper_outcome",
    "chronological_split",
    "chronological_split_from_config",
    "compute_paper_decision",
    "compute_defensive_momentum_decision",
    "compute_defensive_momentum_outcome",
    "compute_paper_outcome",
    "register_experiment",
    "run_market_making_study",
    "run_leveraged_trend_study",
    "run_leveraged_trend_stress",
    "run_defensive_momentum_study",
    "run_frozen_monthly_robustness",
    "verify_defensive_outcome_ledger",
    "run_execution_timing_audit",
    "run_valuation_regime_walk_forward",
    "verify_paper_ledger",
    "verify_outcome_ledger",
]
